[package]
name = "bubblewrap-sys"
version.workspace = true
edition = "2021"
authors.workspace = true
license.workspace = true
description = "Builds and bundles bwrap from bubblewrap"
repository = "https://github.com/boxlite-ai/boxlite"
links = "bubblewrap"
exclude = ["vendor"]

[build-dependencies]
num_cpus = "1.16"
